export const story = [
  [
    "In the vastness of cosmic silence, where the Earth existed as an expansive void—an abyss devoid of life's vibrant hues—a haunting melody echoed through the emptiness, a symphony of desolation unheard in the celestial expanse. This once-thriving world, now reduced to a barren canvas stretched across the tapestry of eternity, lay desolate, bereft of the verdant life that had once adorned the cosmos. Winds, laden with ethereal whispers from distant realms, wove through the emptiness, whispering forgotten tales and secrets from the cosmic memory.",
    "Picture, in the vast expanse, a landscape devoid of any living essence. Here, only the hardened remnants of molten fury stood testament to the capricious touch of cosmic indifference—solidified lava that bore the scars of cosmic tumult. Footsteps, once dancing with the rhythm of life, now left no trace in the stark silence. The touch of verdant life became a distant dream, entangled in the tendrils of cosmic slumber, where the very heartbeat of existence seemed to have succumbed to the relentless march of time.",
    "Yet, in the midst of this celestial abyss, a minuscule emissary descended—a celestial spore cradled in the breath of the cosmos, carrying with it the essence of fungi. With a grace akin to cosmic ballet, this tiny wanderer landed upon the lifeless terrain, a harbinger of transformative dreams—an infinitesimal catalyst that marked the genesis of a cosmic journey, the first whisper of life upon untouched shores of desolation.",
    "Witness, then, the enigmatic communion—the spore's mystic allure resonating across the cosmic ether, calling forth an earthly companion. A resilient plant, a symbiotic algae, drawn by the silent beckoning, converged in an intricate union—a celestial covenant unfolding in the hallowed embrace of the void. This was no ordinary fusion; it was a sacred liaison etched in the whispers of the universe, a mystical embrace transcending the harsh echoes of the surrounding void.",
    "Envision the dance—a gentle sway against the cosmic winds, a harmonious duet amid the solemnity of rocks. The lichen, born of this celestial union, absorbed sunlight with a reverence that echoed through the realms of existence. A celestial waltz ensued, where light seamlessly merged with life, the cosmic choreography of an ethereal dance performed upon the barren stage of the cosmos.",
    "The transformative rite unfolded—the lichen, embodying cosmic symbiosis, embarked on an enchanting process of self-decomposition. A sacrificial dance ensued, birthing the sacred cradle below—a fertile ground ready to nurture life's tender sprouts. The barren rock, cradled in the lichen's silent embrace, pulsed with the promise of rebirth—a cosmic heartbeat echoing through the vast expanse, resonating with the cosmic memory that lingered in the shadows.",
    "In this sacred dance, lichens became the weavers of the xenosere—a mythical process of transformation, a harmonious ballet that heralded the dawn of a new chapter in the cosmic story. They became the architects of the ecosystem's first and monumental step toward life—a beacon in the cosmic tapestry of creation, a testament to the resilience that can emerge from the cosmic void.",
    "Witness how they lived and breathed—a celestial pioneer, a silent witness to the cycles of nature. Their dance breathed life into the atmosphere, and the once-muted landscape burst forth into a vibrant kaleidoscope—an explosion of hues narrating the lichen's sacred pilgrimage. They became the storytellers of cosmic tales, etching their journey into the very fabric of the universe.",
    'As the cosmic tale neared its conclusion, a voice echoed through the cosmic corridors, a proclamation that resonated with the cosmic decree. "This, my friends, is the first step of the xenosere," the voice intoned—a declaration etched in the fabric of existence, signaling the birth of a new era. "This is the first step to create the ecosystem we know," it resonated—a cosmic truth seamlessly woven into the mystic narrative, a testament to the lichen\'s transformative dance eternally etched into the very soul of the cosmic myth. And so, the celestial ballet continued, a dance echoing through the ages, a tale woven with threads of cosmic defiance, ethereal resilience, and the sacred rhythm of the Earth\'s celestial heartbeat—a timeless narrative in the grand symphony of creation.',
  ],

  [
    "In the aeons of cosmic hush, the Earth existed as an expansive void—a barren canvas stretched across the vastness of eternity. A realm devoid of life's vibrant hues, it lay desolate and bereft of the lush tapestry that once adorned the cosmos. Winds, carrying ethereal whispers from distant stars, wove through the emptiness, a haunting melody in a land where the symphony of life had long faded into the echoes of cosmic memory.",
    "Picture, if you will, a landscape devoid of any living essence, where only the hardened remnants of molten fury, solidified lava, bore witness to the harsh touch of cosmic indifference. The once-thriving world reduced to desolation, where the echo of footsteps was swallowed by the stark silence, and the touch of verdant life became a distant dream, entangled in the tendrils of cosmic slumber.",
    "In this abyssal expanse, a celestial ballet unfolded—an ethereal spore descended, a minuscule emissary cradled in the breath of the cosmos. This tiny wanderer bore the essence of fungi, a silent architect with dreams of transforming the barren rock into a sacred haven. With a celestial grace, it alighted upon the lifeless terrain, marking the genesis of a cosmic journey—the first breath of life upon the untouched shores of desolation.",
    "Witness, then, the enigmatic communion—the spore's mystic allure beckoning an earthly companion, a resilient plant, a symbiotic algae. Drawn by the cosmic dance, they converged in an intricate union, intertwining seamlessly into a singular entity—a lichen. This was no mere fusion; it was a celestial covenant etched in the whispers of the universe, a mystical liaison that transcended the harsh echoes of the surrounding void.",
    "Envision the dance—a gentle sway against the cosmic winds, a harmonious duet amid the solemnity of rocks. The lichen, a sacred manifestation of the union, absorbed sunlight with a reverence that echoed through the realms of existence. It drew energy from the very heart of creation, engaging in a celestial waltz where light seamlessly merged with life.",
    "The transformative rite unfolded—the lichen, embodying cosmic symbiosis, embarked on an enchanting process of self-decomposition. A sacrificial dance ensued, birthing the sacred cradle below—a fertile ground ready to nurture life's tender sprouts. The barren rock, cradled in the lichen's silent embrace, pulsed with the promise of rebirth—a cosmic heartbeat echoing through the vast expanse.",
    "In this sacred dance, lichens became the weavers of the xenosere—a mythical process of transformation, a harmonious ballet that heralded the dawn of a new chapter in the cosmic story. They created the starting soil of life, a holy ground upon which the fragile tendrils of existence would find their roots and flourish. Lichens became the architects of the ecosystem's first and monumental step toward life, a beacon in the cosmic tapestry of creation.",
    "Witness how they lived and breathed—a celestial pioneer, a silent witness to the cycles of nature. Their dance breathed life into the atmosphere, and the once-muted landscape burst forth into a vibrant kaleidoscope—an explosion of hues narrating the lichen's sacred pilgrimage.",
    'As the cosmic tale neared its conclusion, a voice echoed through the cosmic corridors, a proclamation that resonated with the cosmic decree. "This, my friends, is the first step of the xenosere," the voice intoned—a declaration etched in the fabric of existence, signaling the birth of a new era. "This is the first step to create the ecosystem we know," it resonated—a cosmic truth seamlessly woven into the mystic narrative, a testament to the lichen\'s transformative dance eternally etched into the very soul of the cosmic myth.',
  ],

  [
    "In the timeless epochs of cosmic hush, where the Earth lay draped in the starkness of barren rock, an eerie desolation spread far and wide. Life's vibrant hues were conspicuously absent from this canvas, and a haunting symphony of winds whispered through the emptiness, carrying tales of a once-thriving world. It was a place where the potential for life remained untapped, lying dormant beneath the weight of a seemingly endless lifelessness.",
    "In this bleak theatre, a celestial ballet unfolded with the descent of a singular spore—a cosmic messenger carried on the gentle breath of the cosmos. This ethereal wanderer, carrying a silent purpose, touched down with delicate grace upon the barren rock—a tiny herald of dreams, a harbinger of transformation. Within the spore's essence resided the spirit of fungi—a quiet architect with the power to stir the dormant spirit of the land and coax life from the arid grip of lifelessness.",
    "The barren rock, kissed by this celestial visitor, experienced a subtle awakening—a murmur of potential echoing through the silent corridors of time. The spore, unassuming yet brimming with cosmic aspirations, nestled itself into the stony embrace of the Earth, whispering cosmic secrets of alchemy and renewal to the land.",
    "As the celestial spore lingered, its mystic allure beckoned other inhabitants of the cosmic realm. Responding to this silent summons was an earthly companion—a resilient plant, a symbiotic algae. Drawn together by the cosmic dance, they converged in a delicate union, intertwining into a singular entity—the lichen. This was no mere merging but a cosmic pact etched in the whispers of the universe—a mystical fusion of fungal spirit and terrestrial kin.",
    "The lichen, born from this sacred union, emerged as a silent witness to the barren land's yearning for life. It became the alchemist of creation, a spectral conductor orchestrating life's symphony from the strands of death. The once desolate terrain now pulsed with newfound vitality, resonating with the ancient rhythm of potential waiting to surge forth.",
    "Picture the dance—a gentle sway against the relentless cosmic winds, a harmonious duet amid the solemnity of rocks. The lichen, in its ethereal embrace, absorbed sunlight with a reverence that echoed through the eons. It drew energy from the very heart of creation, engaging in a celestial waltz where light seamlessly merged with life.",
    "See the transformative rite—the lichen, epitomizing cosmic symbiosis, embarked on the enchanting process of self-decomposition. This sacrificial dance birthed the sacred cradle below, a fertile ground ready to nurture life's fragile sprouts. The once barren rock, cradled in the lichen's silent embrace, pulsed with the promise of rebirth—a cosmic heartbeat, a rhythm echoing through the vast expanse.",
    "Gaze upon the air, once stagnant in the breath of desolation, now awakening to a celestial symphony of oxygen. The lichen's dance breathed life into the atmosphere, and the landscape, once draped in muted tones, burst forth into a vibrant kaleidoscope—a living fresco narrating the lichen's sacred journey.",
    "The lichen, a celestial pioneer, transformed the once-shadowed world into a sanctuary resonating with harmonious chords—an ode to life, a grand composition echoing through the cosmos. The narrative, woven with threads of cosmic defiance, ethereal resilience, and the sacred rhythm of the Earth's celestial heartbeat, echoed through the ages.",
    'And in the midst of the lichen\'s transformative dance, a voice whispered through the cosmic corridors, echoing the promise of renewal and the emergence of life. "This, my friends, is the first step of the xenosere," the voice proclaimed—a cosmic declaration etched in the fabric of existence, signaling the birth of a new chapter, the opening note in the cosmic symphony of creation. "This marks the inception of the ecosystem we know," it resonated—a celestial decree that echoed through the vast expanse, carrying the echoes of the lichen\'s transformative dance into the very soul of the cosmic myth.',
  ],

  [
    "In the aeons of primordial genesis, a cosmic silence enveloped the Earth, veiled in the frigid embrace of lifeless stone. From the celestial realms descended a minuscule emissary, a celestial reverie cast upon the desolation. This ethereal envoy, cloaked in silent purpose, marked a celestial juncture akin to the primal exhalation of life upon untouched shores—a murmured covenant of metamorphosis, a celestial ballet unfolding upon the vast tapestry of nothingness.",
    "Behold the lichen, a mystic duo entwined in a sacred pas de deux upon forsaken rocks—a union of fungal spirit and terrestrial companion. Picture the lichen as the alchemist of creation, a spectral conductor orchestrating life's symphony from the strands of death. In this divine liaison, fungi and earthly essence meld into a singular entity—a living testament to the unity of realms, transcending the harsh whispers of the surrounding void.",
    "Envision the dance—a gentle undulation against the relentless cosmic winds, a harmonious duet amid the solemnity of stones. The lichen, resolute in its embrace, stands unwavering beneath the watchful gaze of the cosmos. It is a dance of resilience, a choreography that speaks to the endurance in the face of cosmic desolation.",
    "Bear witness to the transformative rite—the lichen, with an almost reverential grace, absorbs sunlight, drawing forth energy from the very heart of creation. This is no mere absorption; it is a celestial waltz, where light and life converge seamlessly. The lichen, a silent witness to the cosmic cycles, embarks on an enchanting process of self-decomposition—a sacrificial ballet birthing the sacred cradle below, nurturing life's delicate buds.",
    "This marks the inception of terrestrial alchemy, where death metamorphoses into fertile ground, poised to cradle life's ephemeral blossoms. The once barren rock, now embraced by the lichen's ethereal dance, pulsates with the promise of rebirth—a cosmic heartbeat echoing through the vast expanse, heralding the dawn of a transcendent chapter.",
    "Contemplate the air, once stagnant in the breath of cosmic desolation, now awakening to a celestial symphony of oxygen. The lichen's dance breathes life into the air, and the landscape, once draped in muted tones, erupts into a vibrant kaleidoscope. It is a living fresco, an explosion of hues narrating the lichen's sacred pilgrimage—a tale of defiance against cosmic silence, a narrative of life ascending from the cosmic ashes of nothingness.",
    "Witness, then, the lichen as a celestial harbinger, its humble stride upon barren rock initiating a cosmic metamorphosis. The once-shadowed world, touched by the lichen's grace, resonates with harmonious chords—an ode to life, a grand composition reverberating through the cosmic realms, a testament to the lichen's sacred process, transforming desolate landscapes into sanctified cradles of genesis.",
    "This is no ordinary chronicle—it is an epic, a saga inscribed upon the celestial canvas of creation. The lichen, in its silent dance, emerges as the mystical architect of life, and the once desolate terrain evolves into a cradle for the birth of myriad existences. It is a narrative woven with threads of cosmic defiance, ethereal resilience, and the sacred rhythm of the Earth's celestial heartbeat—a tale that whispers through the aeons, carrying the echoes of the lichen's transformative dance into the very heart of the cosmic genesis.",
  ],

  [
    "In the primordial days, when the Earth lay shrouded in the cold embrace of barren rock, a tiny spore descended like a celestial dream upon the desolate canvas. This minute emissary, imbued with silent purpose, marked a cosmic juncture akin to the first breath of life upon untouched shores – a whisper that promised a transformation, a dance of resurrection upon the stage of nothingness.",
    "Behold the lichen, a mystic duo of fungi and an earthly companion, engaged in a sacred ballet upon the forsaken rocks. Picture the lichen as the alchemist of creation, a silent architect weaving life from the fibers of death. In this divine partnership, the fungi and their earthly kin intertwined, becoming one, a living testament to the unity of realms that defied the harsh whispers of the surrounding silence.",
    "Picture the dance – a gentle sway against the harsh wind, a harmonious duet amidst the solemnity of the rocks. The lichen, resilient in its embrace, stood unwavering under the cosmic gaze. It was a dance of resilience, a choreography that spoke of endurance in the face of desolation.",
    "Now, envision the transformative act – the lichen absorbing sunlight with an almost reverent embrace, drawing energy from the very heart of creation. This was no mere absorption; it was a dance with the cosmos, a cosmic waltz where light merged with life. The lichen, a silent witness to the cycles of nature, began the enchanting process of self-decomposition, a sacrifice that birthed the soil beneath, a sacred cradle for life.",
    "This was the birth of a terrestrial alchemy, where death metamorphosed into fertile ground, ready to nurture life's fragile sprouts. The once barren rock, now cradled in the lichen's gentle dance, began to pulsate with the promise of rebirth. It was a cosmic heartbeat, a rhythm that echoed through the expanse, heralding the dawn of a new chapter.",
    "Now, consider the air, once stagnant in the breath of desolation, awakening to a symphony of oxygen. The lichen's dance had breathed life into the air, and the landscape, once cloaked in muted tones, burst forth into a vibrant kaleidoscope. It was a painting of life, an explosion of hues that whispered the tale of the lichen's sacred journey – a tale of defiance against the silence, a narrative of life rising from the ashes of nothingness.",
    "Witness, then, the lichen as a celestial pioneer, its humble stride upon the barren rock initiating a cosmic metamorphosis. The once-shadowed world, touched by the lichen's grace, resonated with harmonious chords. It was an ode to life, a grand composition that echoed through the cosmos, a testament to the lichen's sacred process of transforming the barren lava into the sacred land of birth.",
    "This was no ordinary story – it was an epic, a saga etched upon the canvas of creation. The lichen, in its silent dance, had become the architect of life, and the once desolate land had become a cradle for the birth of countless lives. It was a narrative woven with threads of defiance, resilience, and the sacred rhythm of the Earth's heartbeat – a tale that whispered through the ages, carrying the echoes of the lichen's transformative dance."
  ], 
  ["000000000000", "1111111111111111", "222222222222222", "33333333333"]
];
//   useEffect(() => {
//     // Randomly select the initial storyIndex only on the first render
//     if (storyIndex === 0) {
//       const randomIndex = Math.floor(Math.random() * stories.length);
//       setStoryIndex(randomIndex);
//     }
//   }, [storyIndex, stories]);